### ISSUE TITLE
GDrive provider crashes cloudmesh as requirements are missing

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-storage#4]
b)  The GDrive provider has been temporarily been disabled, as it does not have the requirements satisfied in requirements.txt and setup.py. Without this it crashes cloudmesh. So please fix. We can not integrate it at this time withoout this update

**Comment by laszewsk** [comment]
File "/Users/grey/Desktop/github/cloudmesh-community/cm/cloudmesh-storage/cloudmesh/storage/Provider.py", line 5, in <module>

    from cloudmesh.storage.provider.gdrive.Provider import \

  File "/Users/grey/Desktop/github/cloudmesh-community/cm/cloudmesh-storage/cloudmesh/storage/provider/gdrive/Provider.py", line 7, in <module>

    from apiclient.http import MediaFileUpload

ModuleNotFoundError: No module named 'apiclient.http'

**Comment by laszewsk** [comment]
Gdrive provider hs been disabled in general storage provider

**Comment by g14uok** [comment]
[requirements.txt](https://github.com/cloudmesh/cloudmesh-storage/files/3052432/requirements.txt)

I have generated the requirements.txt file

**Comment by laszewsk** [comment]
This is not waht we need, we need the minimal requirements for your import statements. not all the imports for everything that is recursively loaded. so look at all imports in your code and only locate the once that you use .... just copy the lines her eand i will add

**Comment by laszewsk** [comment]
for example if i include 

apiclient

it still does not work for me .... not sure why

**Comment by g14uok** [comment]
Below given are the packages I have used in this project. Please try to include these in requirements.txt

```
apiclient==1.0.3
config==0.4.0
docopt==0.6.2
future==0.17.1
google-api-python-client==1.7.8
google-auth==1.6.3
google-auth-httplib2==0.0.3
httplib2==0.12.0
oauth2client==4.1.3
```

**Comment by laszewsk** [comment]
can you try this without frozen versions on your machine, i still get an aerro in apiclient

**Comment by laszewsk** [comment]
I think the bug is here that destroys cms


try:
    import argparse

    flags = argparse.ArgumentParser(parents=[tools.argparser]).parse_args()
except ImportError:
    flags = None


you must not have any commands in a library !

please identify how to pass the flacs through a proper cloudmesh command.

**Comment by laszewsk** [comment]
you need to work on explaining what the flags are so we can identify how to integrate them
