### ISSUE TITLE
box sdk deprecation notice

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-storage#8]
The box sdk has some wanings, 

/Users/grey/.pyenv/versions/ENV3/lib/python3.7/site-packages/boxsdk/pagination/page.py:5
  /Users/grey/.pyenv/versions/ENV3/lib/python3.7/site-packages/boxsdk/pagination/page.py:5: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    from collections import Sequence

/Users/grey/.pyenv/versions/ENV3/lib/python3.7/site-packages/boxsdk/pagination/box_object_collection.py:14
  /Users/grey/.pyenv/versions/ENV3/lib/python3.7/site-packages/boxsdk/pagination/box_object_collection.py:14: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    class BoxObjectCollection(collections.Iterator, object):

-- Docs: https://docs.pytest.org/en/latest/warnings.html

find a way to switch just these warnings of for box sdk but pkeep them for others

**Comment by kelifine** [comment]
Here is what I've found:
[pytest]
filterwarnings =
    ignore::DeprecationWarning:boxsdk.*:

**Comment by laszewsk** [comment]
do you know where we ste this?

we also have one for urllib3

**Comment by laszewsk** [comment]
lopoks like we need something like pytest.ini ? i will see if that works

**Comment by laszewsk** [comment]
fixed
